### ISSUE TITLE
Air Date not Captured by BMT from SageTV on MLB Recording

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ai7/sagetv-for-plexmediacenter#11] opened 2015-03-25 03:37 UTC
```
What steps will reproduce the problem?
1. Using SageTV, record an MLB Baseball game.
2.
3.

What is the expected output? What do you see instead?
I expect the original air date from SageTV to be carried over into BMT like it 
is with all other recorded programs using SageTV.

What version of the product are you using? On what operating system?
Latest Version Available, I always keep my plugins up to date.
Running on Windows 7 Ultimate 64bit

Please provide any additional information below.

I've attached some screen captures to show the missing dates.
```

Original issue reported on code.google.com by `clarence...@gmail.com` on 11 Sep 2013 at 1:42

Attachments:
* [Sage Web Server MLB 2013-08-27 9-13-39 PM.png](https://storage.googleapis.com/google-code-attachments/sagetv-for-plexmediacenter/issue-11/comment-0/Sage Web Server MLB 2013-08-27 9-13-39 PM.png)
* [BMT MLB 2013-08-27 9-12-22 PM.png](https://storage.googleapis.com/google-code-attachments/sagetv-for-plexmediacenter/issue-11/comment-0/BMT MLB 2013-08-27 9-12-22 PM.png)

**Comment by ai7** [comment] 2015-04-27 23:58
BMT is not part of this project. It is a separate SageTV plugin that pulls data from other sources.

sagetv-for-plexmediacenter uses BMT plugin on SageTV to obtain data from Sage (via HTTP interface). What you are reporting may be a bug in BMT itself, but that is not something this plugin can fix. If BMT don't have the correct data, we will not get the correct data.

Closing as not a bug.

**Closed by ai7** 2015-04-27 23:58 UTC
Labels: auto-migrated, Priority-Medium, Type-Defect
